### ISSUE TITLE
Roadmap for first release

### ISSUE THREAD

**Issue by AaronErhardt** [AaronErhardt/Triox#17]
Issue for tracking all features planned to be included in the first release of Triox. Feel free to comment and to suggest or contribute new features.

Contributions are welcome! Also the list can be extended if you feel like we're missing a feature :)

> We use the term apps to refer to modules that add certain services to Triox (similar to Nextcloud apps). We move services into apps to keep our code better organized.

## Planned core apps
- [x] Auth
- [x] Files
- [ ] Settings (user settings and admin panel)
- [ ] WebDAV

## Additional features
- [x] Rate limiting
- [ ] Email verification on sign up
- [ ] Allow file sharing
- [ ] Unify app interfaces and modularize the code
- [ ] Improve database code
- [ ] Further front-end improvements
- [ ] More tests

## Nice to have
- [ ] WASM based front-end
- [ ] Add a Matrix app (for a matrix chat service)
- [ ] Add file sync app
